#steps:

# Install node packages
#- name: node:10.16.3
#  entrypoint: npm
#  args: ['install']

# Build productive files
#- name: node:10.16.3
#  entrypoint: npm
#  args: [ 'run', 'build']

steps:
- name: node
  entrypoint: npm
  args: ['install', 'test', 'run', 'build']
#- name: node
#  entrypoint: npm
#  args: ['test']
#- name: node
#  entrypoint: npm
#  args: ['run', 'build']

#steps:
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['run', 'job1']
#  id: 'job1'
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['run', 'job2']
#  id: 'job2'
#  waitFor: ['-']  # The '-' indicates that this step begins immediately.
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['run', 'done']
#  waitFor: ['job1', 'job2']
